### ISSUE TITLE
Can you update your repo with my paper and code?

### ISSUE THREAD

**Issue by linhduongtuan** [jeremykohn/rid-covid#2]
Dear Mr. Kohn,
It is interesting to see your up-to-date repos and papers associated with Medical Imaging ~ Covid-19.
Your work is valuable to summarize open source codes and relevant researchs
We would like to share our paper and code to you. And hopefully you give us to chance to be apart of your repo.
Here is a link to our paper: https://www.medrxiv.org/content/10.1101/2020.08.13.20173997v1.full.pdf+html
And our source code: https://github.com/linhduongtuan/Covid-19_Xray_Classifier
Best regards.
Linh

**Comment by jeremykohn** [comment]
Thank you, Linh! I've just now updated RID-COVID to include your paper under "[Software Projects and Tutorials](https://github.com/jeremykohn/rid-covid/blob/master/README.md#software-projects-and-tutorials)."
